redis:
  cacheSize: 4
  idleTime: 1

mongo:
  dbName: test
  repository-packages: com.cybernation.testservice.dao

jpa:
  username: postgres
  generate-ddl: true
  show-sql: true
  entity-packages: com.cybernation.testservice.models
  repository-packages: com.cybernation.testservice.dao

descriptors:
  descriptorsMapName: descriptors
  internalIdsMapName: internalIds
  collectionDescriptorsMapName: collection_descriptors
  collectionCoordinatesMapName: collection_descriptors_coordinates_idx

spring:
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.web: DEBUG

custom:
  field-destroyer:
    analyzable-package-prefix: com.cybernation.testservice
  model:
    package-names: com.cybernation.testservice.models