redis:
  uri: redis://localhost:6379
  cacheSize: 4
  idleTime: 1

mongo:
  uri: mongodb://localhost:27017
  dbName: test

elastic:
  hosts:
    -
      host: localhost
      port: 9200
      protocol: http

descriptors:
  descriptorsMapName: descriptors
  internalIdsMapName: internalIds
  collectionDescriptorsMapName: collection_descriptors
  collectionCoordinatesMapName: collection_descriptors_coordinates_idx

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web : DEBUG

custom:
  field-destroyer:
    analyzable-package-prefix: com.cybernation.testservice