redis:
  cacheSize: 4
  idleTime: 1

mongo:
  main-db-name: test
  descriptors-db-name: descriptors
  repository-packages: com.cybernation.testservice.dao

jpa:
  username: postgres
  generate-ddl: true
  show-sql: true
  entity-packages: com.cybernation.testservice.models
  repository-packages: com.cybernation.testservice.dao

elasticsearch:
  repository-packages: com.cybernation.testservice.dao.elasticsearch

descriptors:
  descriptorsMapName: descriptors
  internalIdsMapName: internalIds

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.extremum.everything.aop: DEBUG
    org.springframework.web: DEBUG
    tracer: TRACE

custom:
  sms:
    url: test
    api-key: test
  email:
    url: test
    api-key: test
  auth:
    secret: mytestsecret
  field-destroyer:
    analyzable-package-prefix: com.cybernation.testservice
  model:
    package-names: com.cybernation.testservice.models
